const INVOICE_STATES = {
  SUBIDA: 'SUBIDA',
  EN_PROCESO: 'EN_PROCESO',
  PROCESADA_IA: 'PROCESADA_IA',
  PENDIENTE_REVISION: 'PENDIENTE_REVISION',
  VALIDADA: 'VALIDADA',
  RECHAZADA: 'RECHAZADA',
  SINCRONIZADA: 'SINCRONIZADA',
  ERROR_PROCESAMIENTO: 'ERROR_PROCESAMIENTO',
};

const JOB_STATES = {
  PENDIENTE: 'PENDIENTE',
  EN_PROCESO: 'EN_PROCESO',
  COMPLETADO: 'COMPLETADO',
  ERROR: 'ERROR',
};

const USER_ROLES = {
  ADMIN: 'ADMIN',
  CONTABILIDAD: 'CONTABILIDAD',
  REVISOR: 'REVISOR',
  LECTURA: 'LECTURA',
};

const INVOICE_TYPES = {
  COMPRA: 'compra',
  VENTA: 'venta',
};

const ALLOWED_FILE_TYPES = ['application/pdf', 'image/jpeg', 'image/png'];

const MAX_FILE_SIZE = parseInt(process.env.MAX_FILE_SIZE || '10485760', 10); // 10MB

module.exports = {
  INVOICE_STATES,
  JOB_STATES,
  USER_ROLES,
  INVOICE_TYPES,
  ALLOWED_FILE_TYPES,
  MAX_FILE_SIZE,
};
